--query returns list of PRIMARY KEYs for table
select S.RDB$FIELD_NAME
from RDB$INDEX_SEGMENTS as S
left join RDB$RELATION_CONSTRAINTS as RC on (RC.RDB$INDEX_NAME = S.RDB$INDEX_NAME)
where RC.RDB$RELATION_NAME = @TABLE_NAME and
      RC.RDB$CONSTRAINT_TYPE = 'PRIMARY KEY'
ORDER BY RDB$FIELD_POSITION;